// OWNER: character editor (IDEA-025, dev-only).
// "Copy full file": produces the COMPLETE characters.ts text with the current
// edits already injected into the right builder, so applying your work is
// paste-the-whole-file instead of hunting for the right line. The edit block
// is inserted just before the builder's final `return g;` — at that point
// every part and material const is in scope, and setting absolute values
// there overrides the authored ones, reproducing exactly what the editor
// shows (the editor records absolute post-build values).
//
// A block left by a PREVIOUS session is deliberately kept: it was part of the
// source this editor session loaded, so its effect is already inside the
// baselines — the new block only carries this session's deltas on top of it.
// Within one session the raw source never changes, so repeated copies always
// yield "original file + one block with ALL current edits" (no stacking).
import charactersSource from "../render/characters.ts?raw";
import { type EditLog } from "./editLog";
import { collectEditBlocks } from "./codegen";
import { findFunctionRange } from "./sourceParse";

const BLOCK_OPEN = "// --- Character Editor edits (generated by /editor/) ---";
const BLOCK_CLOSE = "// --- end Character Editor edits ---";

/**
 * The full modified characters.ts, or null when the builder (or its
 * `return g;`) can't be located — the caller falls back to telling the user
 * to use the snippet instead.
 */
export function generateFullFile(log: EditLog, builderName: string): string | null {
  const src = charactersSource;
  const range = findFunctionRange(src, builderName);
  if (!range) return null;

  const body = src.slice(range.fnStart, range.end);
  const returnIdx = body.lastIndexOf("\n  return g;");
  if (returnIdx === -1) return null;
  const insertAt = range.fnStart + returnIdx + 1; // just after that "\n"

  const lines = collectEditBlocks(log, builderName)
    .map((block) => block.map((l) => `  ${l}`).join("\n"))
    .join("\n\n");
  const editBlock = `  ${BLOCK_OPEN}\n${lines}\n  ${BLOCK_CLOSE}\n\n`;

  return src.slice(0, insertAt) + editBlock + src.slice(insertAt);
}
