// OWNER: character editor (IDEA-025, dev-only).
// "Copy full file": produces the COMPLETE characters.ts text with the current
// edits already injected into the right builder, so applying your work is
// paste-the-whole-file instead of hunting for the right line. The edit block
// is inserted just before the builder's final `return g;` — at that point
// every part and material const is in scope, and setting absolute values
// there overrides the authored ones, reproducing exactly what the editor
// shows (the editor records absolute post-build values).
//
// A block left by a PREVIOUS session is deliberately kept: it was part of the
// source this editor session loaded, so its effect is already inside the
// baselines — the new block only carries this session's deltas on top of it.
// Within one session the raw source never changes, so repeated copies always
// yield "original file + one block with ALL current edits" (no stacking).
import { sourceTextFor } from "./sources";
import { type SavableFile } from "./saveFile";
import { type EditLog } from "./editLog";
import { collectEditBlocks, addedPartLines } from "./codegen";
import { findFunctionRange } from "./sourceParse";
import { applyEditLog, type ApplyReport, type EditLogInput } from "./sourceRewrite";

/**
 * IDEA-025 v3 — what "💾 Save" now does: apply the session's edits to the REAL
 * definitions in characters.ts, rather than appending the override block that
 * generateFullFile() below produces.
 *
 * Returns the new file text PLUS an honest account of what could not be
 * written in place (loop-built mirrored parts, skin-owned colours, unnamed
 * nodes) so the editor can say so instead of flashing "Saved ✓" over a change
 * that never landed.
 */
export function applyEditsInPlace(
  log: EditLog,
  builderName: string,
  file: SavableFile,
): ApplyReport {
  const input: EditLogInput = {
    transforms: [...log.transformEdits.values()].map((r) => ({
      varName: r.varName,
      isAutoNamed: r.isAutoNamed,
      locator: r.locator,
      position: r.position,
      rotation: r.rotation,
      scale: r.scale,
      visible: r.visible,
    })),
    deletions: [...log.deletedOriginals.values()].map((r) => ({
      varName: r.varName,
      isAutoNamed: r.isAutoNamed,
      locator: r.locator,
    })),
    additions: log.addedParts.map((p) => ({ name: p.name, lines: addedPartLines(p) })),
    materials: [...log.materialEdits.values()].map((r) => ({
      varName: r.info.varName,
      color: r.color,
      roughness: r.roughness,
    })),
  };
  return applyEditLog(sourceTextFor(file), builderName, input);
}

const BLOCK_OPEN = "// --- Character Editor edits (generated by /editor/) ---";
const BLOCK_CLOSE = "// --- end Character Editor edits ---";

/**
 * The full modified characters.ts, or null when the builder (or its
 * `return g;`) can't be located — the caller falls back to telling the user
 * to use the snippet instead.
 */
export function generateFullFile(
  log: EditLog,
  builderName: string,
  file: SavableFile,
): string | null {
  const src = sourceTextFor(file);
  const range = findFunctionRange(src, builderName);
  if (!range) return null;

  const body = src.slice(range.fnStart, range.end);
  const returnIdx = body.lastIndexOf("\n  return g;");
  if (returnIdx === -1) return null;
  const insertAt = range.fnStart + returnIdx + 1; // just after that "\n"

  const lines = collectEditBlocks(log, builderName)
    .map((block) => block.map((l) => `  ${l}`).join("\n"))
    .join("\n\n");
  const editBlock = `  ${BLOCK_OPEN}\n${lines}\n  ${BLOCK_CLOSE}\n\n`;

  return src.slice(0, insertAt) + editBlock + src.slice(insertAt);
}
