// Scratch: dump the BUILT part tree of an enemy skin as a `parts.json` manifest
// for img2threejs's `check_part_coverage.py`.
//
// Written by hand first, and that was the wrong instrument: a hand-written
// manifest is a claim about the model rather than a reading of it, and the
// gate's whole purpose is to catch a component that was specified and then
// quietly never built. A manifest typed from the same intention that wrote the
// builder cannot catch that. This walks the real Group.
//
//   npx tsx scripts/_scratch-burger-manifest.ts [skin] [out]
import * as THREE from "three";
import { writeFileSync } from "node:fs";
import { makeEnemy } from "../src/render/characters";

const skin = process.argv[2] ?? "burger";
const out = process.argv[3] ?? `.img2threejs/${skin}/parts.json`;

const g = makeEnemy(skin, 0xe8615f);
g.updateMatrixWorld(true);

type Part = { name: string; kind: string; triangles: number; children: number };
const parts: Part[] = [];
let unnamed = 0;
let integral = 0;

g.traverse((o) => {
  const isMesh = o instanceof THREE.Mesh;
  if (isMesh) {
    integral++;
    if (!o.name) {
      unnamed++;
      return;
    }
  }
  if (!o.name) return;
  let tris = 0;
  o.traverse((c) => {
    if (!(c instanceof THREE.Mesh)) return;
    const geo = c.geometry;
    tris += geo.index ? geo.index.count / 3 : geo.attributes.position.count / 3;
  });
  parts.push({
    name: o.name,
    kind: isMesh ? "part" : "assembly",
    triangles: Math.round(tris),
    children: o.children.length,
  });
});

writeFileSync(
  out,
  JSON.stringify(
    {
      model: skin,
      note:
        "Generated by scripts/_scratch-burger-manifest.ts from the real makeEnemy() " +
        "output — a READING of the built tree, not a claim about it. Regenerate " +
        "after any change to the builder rather than editing this file.",
      parts,
      unnamedMeshes: unnamed,
      integralMeshes: integral,
    },
    null,
    2,
  ) + "\n",
);
console.log(`${out}: ${parts.length} named parts, ${integral} meshes, ${unnamed} unnamed`);
